### ISSUE TITLE
Reflection Image Capture

### ISSUE THREAD

**Issue by Pushkar2307** [ChenyangLEI/flash-reflection-removal#2]
Hi! Thank you for sharing this amazing work.

I wanted to know how you capture the "extra reflection image"(Ra) mentioned in the paper?
Do you use a black cloth behind glass to do so?

Thanks,
Pushkar

**Comment by ChenyangLEI** [comment]
Yes, I use a black cloth behind glass to do so. I follow the pipeline of this paper: https://openaccess.thecvf.com/content_CVPR_2020/papers/Lei_Polarized_Reflection_Removal_With_Perfect_Alignment_in_the_Wild_CVPR_2020_paper.pdf

**Comment by Pushkar2307** [comment]
Okay, thank you!
