### ISSUE TITLE
anybody release the version of pytorch?

### ISSUE THREAD

**Issue by adamas-v** [ChenyangLEI/flash-reflection-removal#4]

**Comment by ChenyangLEI** [comment]
Sorry for the late reply.

Currently nobody provides the pytorch version. However, we will release a pytorch version in a month.

**Comment by zhuxyme** [comment]
> Sorry for the late reply.
> 
> Currently nobody provides the pytorch version. However, we will release a pytorch version in a month.

already May 2022, where is the pytorch version

**Comment by ChenyangLEI** [comment]
It is released now.

**Comment by ChenyangLEI** [comment]
It is released today. Thank for your reminder.

zhuxyme ***@***.***> 于2022年3月10日周四 10:49写道：
