### ISSUE TITLE
names in the CSV files

### ISSUE THREAD

**Issue by xyIsHere** [ChenyangLEI/flash-reflection-removal#5]
Dear author,

Thank you for your work and the torch implementation. I'm confused about the column names in the csv files that your provided along with the test data (real2) such as the sf, sab_R and sab_T. Could you provide some detailed explanation about the information in this file? 

Thanks a lot!

**Comment by xjiangan** [comment]
This test data is for our new paper, which handles the misalignment between flash and no-flash image in handheld photography.   
The paper will be on arxiv soon.  
  
The csv files records information about misaligned pairs. The prefix "s" is abbreviation for "shifted", which means that field is about the misaligned part.   
Other abbreviations are:
| Abbreviation  | Full   |
|---|---|
| ab/a  | Ambient  |
|  f | Flash  |
|  R | Reflection   |
| T | Transmission|
| ev |Exposure value|

**Comment by xyIsHere** [comment]
Thanks a lot. Looking forward for the new paper coming out.
